[package]
name = "hh-execute"
version = "0.1.0"
authors = ["azjezz <azjezz@protonmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3" }
shiplift = { version = "0.7" }
serde_json = { version = "1.0" }
